# Generated by Django 5.2.9 on 2025-12-21 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SportManage", "0008_remove_note_from_sp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sportrecord",
            index=models.Index(
                fields=["user", "date"], name="SportManage_user_id_5ef1ae_idx"
            ),
        ),
    ]
