# Generated by Django 5.2.9 on 2025-12-19 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SleepManage", "0006_sleep_record_triggers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleeprecord",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sleeprecord",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="睡眠时长（小时）", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sleeprecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sleep_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
