# Generated by Django 5.2.9 on 2025-12-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SleepManage", "0009_sleep_record_procedures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sleeprecord",
            name="note",
        ),
    ]
