# Generated by Django 5.2.9 on 2025-12-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SleepManage", "0010_remove_sleeprecord_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sleeprecord",
            name="duration",
        ),
    ]
