# Generated by Django 5.2.4 on 2025-07-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="realName",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="真实姓名"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="角色"
            ),
        ),
    ]
