# Generated by Django 5.2.4 on 2025-08-02 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0004_friend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friend",
            unique_together={("from_user", "to_user", "status")},
        ),
    ]
