# Generated by Django 5.2.5 on 2025-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0005_alter_friend_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_calories_burn_goal",
            field=models.FloatField(
                default=500, verbose_name="每日运动消耗卡路里目标（千卡）"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_calories_intake_goal",
            field=models.FloatField(
                default=2000, verbose_name="每日摄入卡路里目标（千卡）"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_sleep_hours_goal",
            field=models.FloatField(default=8, verbose_name="每日睡眠时长目标（小时）"),
        ),
    ]
