# Generated by Django 5.2.5 on 2025-12-25 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0019_add_sp_update_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user', 'status', 'created_at')},
        ),
    ]
