# Generated by Django 5.2.9 on 2025-12-21 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActivityComment", "0004_transaction_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["activity_type", "activity_id"],
                name="ActivityCom_activit_5a895d_idx",
            ),
        ),
    ]
