# Generated by Django 5.2.4 on 2025-07-27 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("edible_portion", models.FloatField(default=1.0)),
                (
                    "water_content",
                    models.FloatField(default=0, help_text="水含量 (克)"),
                ),
                ("energy_kj", models.FloatField(default=0, help_text="能量 (千焦)")),
                ("energy_kcal", models.FloatField(default=0, help_text="能量 (千卡)")),
            ],
        ),
        migrations.CreateModel(
            name="DietRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "早餐"),
                            ("lunch", "午餐"),
                            ("dinner", "晚餐"),
                        ],
                        max_length=10,
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("quantity_in_grams", models.FloatField()),
                (
                    "estimated_calories",
                    models.FloatField(help_text="估算摄入热量 (kcal)"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "手动录入"), ("ai", "系统推荐")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DietManage.nutritionfood",
                    ),
                ),
            ],
        ),
    ]
