# Generated by Django 5.2.4 on 2025-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DietManage", "0002_mealrecord_mealitem_delete_dietrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionfood",
            name="energy_get_kcal",
            field=models.FloatField(default=0, help_text="能量 (千卡)"),
        ),
        migrations.AddField(
            model_name="nutritionfood",
            name="energy_get_kj",
            field=models.FloatField(default=0, help_text="能量 (千焦)"),
        ),
    ]
