# Generated by Django 5.2.4 on 2025-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DietManage", "0003_nutritionfood_energy_get_kcal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="estimated_water",
            field=models.FloatField(default=0, help_text="克(g)"),
        ),
        migrations.AddField(
            model_name="nutritionfood",
            name="water_get",
            field=models.FloatField(default=0, help_text="水分 (克)"),
        ),
        migrations.AlterField(
            model_name="mealitem",
            name="estimated_calories",
            field=models.FloatField(default=0, help_text="千卡(kcal)"),
        ),
    ]
