# Generated by Django 5.2.4 on 2025-07-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "DietManage",
            "0004_mealitem_estimated_water_nutritionfood_water_get_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealrecord",
            name="created_at",
        ),
    ]
