# Generated by Django 5.2.4 on 2025-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DietManage", "0006_mealrecord_created_at_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
