# Generated by Django 5.2.4 on 2025-08-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DietManage", "0007_alter_mealrecord_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
