# Generated by Django 5.2.9 on 2025-12-21 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DietManage", "0015_transaction_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mealrecord",
            index=models.Index(
                fields=["user", "date"], name="DietManage__user_id_c2a08e_idx"
            ),
        ),
    ]
