# Generated by Django 5.2.4 on 2025-08-05 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("sleep_prediction", "睡眠质量预测"),
                            ("sleep_sport_correlation", "睡眠运动关联性"),
                            ("health_trend", "健康趋势分析"),
                            ("calorie_analysis", "卡路里分析"),
                            ("sleep_quality_score", "睡眠质量评分"),
                        ],
                        max_length=50,
                    ),
                ),
                ("result_data", models.JSONField(help_text="分析结果数据")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "analysis_type")},
            },
        ),
    ]
